services:
  db:
    image: postgres:15-alpine
    container_name: flightdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flightdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  ray:
    build:
      context: .
      dockerfile: Dockerfile.ray
    container_name: flightray
    shm_size: "2gb"
    environment:
      MODEL_PATH: models/modele.pkl
    ports:
      - "8265:8265"  # Ray Dashboard
      - "6379:6379"  # Ray Redis/GCS
      - "10001:10001"  # Ray Client API (port de connexion principal)
    volumes:
      - ./models:/app/models
    command: bash -c "ray start --head --port=6379 --ray-client-server-port=10001 --dashboard-host=0.0.0.0 --dashboard-port=8265 --object-store-memory=1000000000 --include-dashboard=true && sleep 3 && ray status && tail -f /dev/null"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8265 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  api:
    build: .
    container_name: flightapi
    depends_on:
      db:
        condition: service_healthy
      ray:
        condition: service_healthy
    shm_size: "2gb"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/flightdb
      RAY_ADDRESS: ray://ray:10001
      PORT: 8000
      HOST: 0.0.0.0
      ENV: production
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./models:/app/models
    networks:
      - app-network
    command: /bin/bash -c ". .venv/bin/activate && python scripts/setup_database.py && python main.py"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
